apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flame-pvc-claim
  namespace: kh
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  volumeName: flame-pv-volume