apiVersion: v1
kind: PersistentVolume
metadata:
  name: flame-pv-volume
  namespace: kh
  labels:
    type: local-path
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
