apiVersion: v1
kind: Namespace
metadata:
  name: kh
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: etransafe
  namespace: kh
---
apiVersion: v1
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: kh
  name: etransafe-khr-service-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: etransafe-khr-read-services
  namespace: kh
subjects:
- kind: ServiceAccount
  name: etransafe # Name is case sensitive
  apiGroup: ""
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: etransafe-khr-service-reader # this mu
